name: "Unit and E2E Tests"

on: push

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Test
        run: npm test
  e2e-tests:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run cypress